import { BookCartProvider } from "@/contexts/BookCartContext";
import { Header } from "@/components/organisms/Header";
import { Footer } from "@/components/organisms/Footer";
import "./globals.css";
import type React from "react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <BookCartProvider>
          <div className="flex flex-col min-h-screen">
            <Header />

            <div className="flex-1 bg-background pt-12 pb-8 px-4 sm:px-6 lg:px-8">
              <div className="max-w-6xl mx-auto">
                <div className="w-full max-w-4xl mx-auto">
                  <main className="pt-4">{children}</main>
                </div>
              </div>
            </div>

            <Footer />
          </div>
        </BookCartProvider>
      </body>
    </html>
  );
}
