import { BookCartProvider } from "@/contexts/BookCartContext";
import { Header } from "@/components/organisms/Header";
import "./globals.css";
import type React from "react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <BookCartProvider>
          <Header />
          <div className="min-h-screen bg-background py-12 px-4 sm:px-6 lg:px-8">
            <div className="max-w-6xl mx-auto">
              <div className="w-full max-w-4xl mx-auto">
                <main className="py-16 h-[calc(100vh-5rem)]">{children}</main>
              </div>
            </div>
          </div>
        </BookCartProvider>
      </body>
    </html>
  );
}
